### PR TITLE
new version of app.py

### PR DESCRIPTION
**Pull request by I-Hong**
appp_trackerV01

### CODE REVIEW

**Comment by xwu0226** [comment]
@rhagarty This is an enhancement of the published web-app code pattern.

**Comment by I-Hong** [comment]
This is a different version for web-app. I create it in a new file by adding ''opencv tracking'' to reduce latency.

**Comment by ajbozarth** [comment]
FYI despite `app_trackerV01.py` being executable it fails to run as `./app_trackerV01.py` only as `python app_trackerV01.py` the returned error is:
```
./app_trackerV01.py: line 1: import: command not found
from: can't read /var/mail/flask
from: can't read /var/mail/queue
./app_trackerV01.py: line 4: try:: command not found
from: can't read /var/mail/flask.ext.socketio
./app_trackerV01.py: line 6: except: command not found
from: can't read /var/mail/flask_socketio
from: can't read /var/mail/gevent
./app_trackerV01.py: line 11: syntax error near unexpected token `app'
./app_trackerV01.py: line 11: `app = Flask(__name__)'
```

**Comment by ajbozarth** [comment]
This does not run without running `pip install opencv-contrib-python` but it isn't documented

**Comment by ajbozarth** [comment]
Not sure why this is only an issue now, but the web cam doesn't work in safrai anymore due to the use of a deprecated function in `webapp_video.js`. The function `Navigator.getUserMedia` has been replaced by `navigator.mediaDevices.getUserMedia` but even after fixing this the webcam is still a black screen. Oddly enabling the webcam in another browser fixes it in safari. Given the percentage of users on MacOS we should always make sure this runs in Safari and not just Chrome and FF. Therefore this is currently broken

**Comment by I-Hong** [comment]
Thanks, Alex. It works for my either Safari or Chrome. Let me figure out the issue and fix it.

**Pull request closed without merging**
