### PR TITLE
Fix safari issue by changing resolution

### PR DESCRIPTION
**Pull request by djalova**
Safari only accepts a few video resolutions (https://webrtchacks.com/safari-webrtc/). I changed the resolution from 1024x576 to 960x540.

### CODE REVIEW

**Comment by I-Hong** [comment]
Thanks @djalova , it will be great if the video resolution can be dynamic according the size of the browser; using `%` instead of a fixed number.

**Comment by djalova** [comment]
Made an update to change resolution only if Safari is detected. I think Safari is more strict with webcam resolutions, so having just a 16:9 ratio won't work.

I also edited the link to the source code to point to this repo.

**Comment by ajbozarth** [comment]
Code LGTM, I'll check it out and try running it tomorrow

**Comment by I-Hong** [comment]
LGTM, but, do we need to test on Firefox and Edge also? Or, they should be fine when Chrome & Safari are good.

**Comment by ajbozarth** [comment]
I tested it on Safari, Chrome, and IBM FF, so we're probably good

**Comment by I-Hong** [comment]
Thanks @ajbozarth, it's good to merge, right?

**Pull request merged**
