### PR TITLE
Add futures to requirements.txt

### PR DESCRIPTION
**Pull request by djalova**
Since the base image in the Dockerfile we're using uses python 3, we need to add a conditional to install `futures` only if the python version is <3.0.

### CODE REVIEW

**Comment by djalova** [comment]
Addresses #39

**Comment by xuhdev** [comment]
Do we actually support Python < 3.0 in this model?

**Comment by I-Hong** [comment]
It'd be good if we support both of 2.x and 3.x.

**Comment by MLnick** [comment]
I think we don’t really need to support 2.x - it’s end of life Jan 2020 and
within the docker container I see no benefit in supporting multiple major
versions

**Comment by MLnick** [comment]
I guess it's a small enough change so that we can do it here.

As a general rule I don't think we need to go out of our way to support Python <3

**Comment by I-Hong** [comment]
@xuhdev, can you review it as well?

**Pull request merged**
